name: cancellation_token_http
version: 0.13.4
homepage: https://github.com/jonathanpetercole/dart-cancellation-token-http
description: A fork of Dart's HTTP package with request cancellation using cancellation_token.

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  async: ^2.5.0
  cancellation_token: ^1.3.3
  http_parser: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  fake_async: ^1.2.0
  lints: ^1.0.0
  shelf: ^1.1.0
  test: ^1.16.0
