name: cancellation_token_http_client_conformance_tests
description: >-
  A library that tests whether implementations of package:cancellation_token_http's `Client` class
  behave as expected.
repository: https://github.com/JonathanPeterCole/dart-cancellation-token-http/tree/main/pkgs/http_client_conformance_tests

publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  async: ^2.8.2
  cancellation_token_http: ^2.1.0
  dart_style: ^2.2.3
  stream_channel: ^2.1.1
  test: ^1.21.2

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
