name: http_client_conformance_tests
description: >-
  A library that tests whether implementations of package:cancellation_token_https's `Client` class
  behave as expected.
publish_to: none
repository: https://github.com/dart-lang/http/tree/master/pkgs/http_client_conformance_tests

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  async: ^2.8.2
  cancellation_token_http: ^1.1.0
  test: ^1.21.2

dev_dependencies:
  dart_style: ^2.2.3
  lints: ^1.0.0
