name: cancellation_token_http
version: 1.4.0
homepage: https://github.com/JonathanPeterCole/dart-cancellation-token-http/tree/main/pkgs/http
description: A fork of Dart's HTTP package with request cancellation using cancellation_token.

environment:
  sdk: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  async: ^2.5.0
  cancellation_token: ^2.0.0
  http_parser: ^4.0.0
  meta: ^1.3.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  fake_async: ^1.2.0
  http_client_conformance_tests:
    path: ../http_client_conformance_tests/
  shelf: ^1.1.0
  stream_channel: ^2.1.0
  test: ^1.16.0
